---
title: "Introduction to R: Week 4 Practice"
author: "Maria Doyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_notebook:
    toc: yes
    toc_float: yes
    toc_depth: 2
subtitle: Interactive volcano plot challenge
---

#### Challenge

You've learnt how to made a volcano plot of your RNA-seq results in this course and you can now create static plots that you can include in your paper. However, you'd like to also be able to interactively explore the plot to see what genes the points represent.

The aim of this challenge is to generate an **interactive** volcano plot of the luminal RNA-seq results, similar to below, using the cool **plotly** package. 


```{r echo = FALSE}
library(tidyverse)
library(plotly)
de_results <- read_tsv("/training/r-intro-tidyverse/data/limma-voom_luminalpregnant-luminallactate.tsv.gz")
de_results <- mutate(de_results, signif=ifelse((adj.P.Val < 0.05 & logFC > 1), "Up", ifelse((adj.P.Val < 0.05 & logFC < -1), "Down", "Not signif")))
p <- ggplot(data=de_results, mapping=aes(x=logFC, y=-log10(P.Value), colour=signif, Gene=SYMBOL)) +
  geom_point() +
  scale_colour_manual(values=c("Up"="red", "Not signif"="grey", "Down"="blue"))
ggplotly(p, tooltip="Gene")
```


### Steps

* To make the interactive plot you will need to load both the tidyverse and the plotly packages.
* Then first make a static volcano plot for the `limma-voom_luminalpregnant-luminallactate.tsv.gz` file, as you did previously in the volcanoplot tutorial. You can colour the Up, Down and Not signif genes as before but there is no need to add labels (no need to use geom_text or geom_text_repel).
* Then take a look at the help for the `ggplotly` function, especially the `tooltip` argument (and Google) and see if you can make the volcano plot interactive.
* Email the instructor your code.
